name: flutter_commons_lang
description: commons_lang for flutter, utils for op DateTime, Stringflutter packages pub publish --dry-run
version: 0.0.1
author: cRazyx <crz365966834@qq.com>
homepage: https://github.com/crazy365966834/flutter_datetime_tools

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"